# Generated by Django 4.2.3 on 2023-07-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperCapsule', '0002_article_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
