# Generated by Django 4.2.3 on 2023-07-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperCapsule', '0004_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
