# Generated by Django 4.2.3 on 2023-07-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperCapsule', '0006_article_slug_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
