# Generated by Django 4.2.3 on 2023-07-18 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paperCapsule', '0007_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
