# Generated by Django 4.2.3 on 2023-07-18 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paperCapsule', '0009_article_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archived',
            field=models.ManyToManyField(blank=True, related_name='archived_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
