# Generated by Django 4.2.3 on 2023-07-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperCapsule', '0011_article_highlights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
