# Generated by Django 4.2.3 on 2023-07-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperCapsule', '0012_remove_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
