# Generated by Django 4.2.3 on 2023-07-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperCapsule', '0013_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
