# Generated by Django 4.2 on 2023-04-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saved',
            new_name='Article',
        ),
    ]
