# Generated by Django 4.2 on 2023-04-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_savedarticle_favoritearticle_archivedarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedarticle',
            name='saved_date',
        ),
    ]
