# Generated by Django 4.2 on 2023-04-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_savedarticle_saved_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritearticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='favoritearticle',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArchivedArticle',
        ),
        migrations.DeleteModel(
            name='FavoriteArticle',
        ),
    ]
