# Generated by Django 4.2 on 2023-05-04 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_favoritearticle_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedarticle',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
