# Generated by Django 4.2 on 2023-05-06 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_archiveddarticle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchiveddArticle',
            new_name='ArchivedArticle',
        ),
    ]
