# Generated by Django 4.2 on 2023-05-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_article_is_archived_article_is_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_archived',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='is_saved',
            new_name='saved',
        ),
    ]
