# Generated by Django 4.2 on 2023-05-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_is_archived_article_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='archived',
            field=models.BooleanField(default=True),
        ),
    ]
