# Generated by Django 4.2 on 2023-05-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_article_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
